### ISSUE TITLE
Shinobi Pro - Docker Hub readme

### ISSUE THREAD

**Issue by nickcj931** [SpaceinvaderOne/Docker-Templates-Unraid#1]
Thanks for making this container available on unraid! 

Just a thought of maybe adding to the guide on docker hub (the github link doesnt work) on how to access super user as I didnt have a clue without searching the original shinobi docker page.

Something like the below:

### Shinobi admin access
To access Shinobi super admin GUI head over to ```http://xxx.xxx.xxx.xxx:8080/super```
**Username:** as defined by ```ADMIN_USER``` environmental variable
**Password:** as defined by ```ADMIN_PASSWORD``` envrionmental variable

Keep up the ace work fella!!

**Comment by SpaceinvaderOne** [comment]
done -thankyou
